//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyFinancialAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceSheet
    {
        public int Id { get; set; }
        public string Ticker { get; set; }
        public string CurrentAssets { get; set; }
        public string FundsAndInvestments { get; set; }
        public string FixedAssets { get; set; }
        public string IntangibleAssets { get; set; }
        public string OtherAssets { get; set; }
        public string TotalAssets { get; set; }
        public string Currentliabilities { get; set; }
        public string Long_Termliabilities { get; set; }
        public string VariousPreparations { get; set; }
        public string Otherliabilities { get; set; }
        public string Totalliabilities { get; set; }
        public string CompanyStock { get; set; }
        public string AdditionalPaid_InCapital { get; set; }
        public string RetainedEarnings_ { get; set; }
        public string Stockholders_EquitiesAdjustments { get; set; }
    }
}
