//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyFinancialAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDataTable
    {
        public int Id { get; set; }
        public Nullable<double> Ticker { get; set; }
        public Nullable<double> Name { get; set; }
        public Nullable<double> Date { get; set; }
        public Nullable<double> WorkingCapital { get; set; }
        public Nullable<double> RetainedEarning { get; set; }
        public Nullable<double> EBIT { get; set; }
        public Nullable<double> TotalAsset { get; set; }
        public Nullable<double> TotalLiability { get; set; }
        public Nullable<double> GrossSales { get; set; }
        public Nullable<double> MarketValue { get; set; }
        public Nullable<double> CompanyStock { get; set; }
        public Nullable<double> StockPrice { get; set; }
        public string ZValue { get; set; }
        public Nullable<double> Equity { get; set; }
    }
}
