//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyFinancialAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeStatement
    {
        public int Id { get; set; }
        public string Ticker { get; set; }
        public string OperatingRevenue { get; set; }
        public string CostOfGoodsSold { get; set; }
        public string Grossprofit { get; set; }
        public string RealizedGainFromInter_affiliateAccounts { get; set; }
        public string UnrealizedGainFromInter_affiliateAccounts { get; set; }
        public string OperatingExpenses { get; set; }
        public string OperatingIncome { get; set; }
        public string Non_OperatingIncome { get; set; }
        public string Non_OperatingExpenses { get; set; }
        public string IncomeBeforeTaxFromContinuingOperations { get; set; }
        public string IncomeTaxExpense { get; set; }
        public string IncomeFromContinuingOperations { get; set; }
        public string IncomeOnDiscontinuedOperations { get; set; }
        public string ExtraordinaryItems { get; set; }
        public string MulativeEffectOfChangeInAccountingPrinciple { get; set; }
        public string NetIncome { get; set; }
        public string EarningPerShare { get; set; }
    }
}
